server:
  host: 127.0.0.1
  port: 8080
  secret: 'secret'
  filePath: '/tmp/WiFiGhost'

mac:
  oui: "6c:e9:07" #Nokia

# Configuracion de la base de datos
database:
  name: wifiGhostdb
  user: wGhost
  password: WiFiGhost
